### ISSUE TITLE
Weird behaviour with Timeout.timeout

### ISSUE THREAD

**Issue by Nakilon** [splattael/minitest-around#38]
I'm using minitest-around to limit integration tests duration. But suddenly discovered that if the timeout is happening inside the begin-rescue, it does not stop. But if it's only inside the do-rescue, it's fine. I don't understand why.

```ruby
require "maxitest/autorun"

M = Struct.new(:m).new

require "timeout"

describe "" do
  before{ puts "#{Time.now} test start" }

  around do |test|
    Timeout.timeout 1 do
      M.stub :m, ->&_{ sleep 2 } do
        puts "#{Time.now.to_f} vvv"
        test.call
        puts "#{Time.now.to_f} ^^^"
      end
    end
  end

  it "1" do
    M.m do
    rescue
      sleep 1
      flunk "test 1: slept 1 more second?"
    end
  end

  it "2" do
    begin
      M.m do
      end
    rescue
      sleep 1
      flunk "test 2: slept 1 more second!"
    end
  end

end
```
```none
2024-02-01 16:56:43 +0300 test start
1706795803.772171 vvv
1706795804.776078 ^^^
E2024-02-01 16:56:44 +0300 test start
1706795804.776897 vvv
1706795806.782805 ^^^
F

Finished in 3.012514s, 0.6639 runs/s, 0.3319 assertions/s.

  1) Error:
#test_0001_1:
Timeout::Error: execution expired
    ./test_.rb:12:in `sleep'
    ./test_.rb:12:in `block (4 levels) in <main>'

  2) Failure:
#test_0002_2 [./test_.rb:34]:
test 2: slept 1 more second!
```

In real case I have multiple begin-rescue layers with retry, so my test hangs (

**Comment by grosser** [comment]
seems to not be the rescue
```
Timeout.timeout 1 do
  begin
    sleep 2
  rescue
  end
end
```

best simplify this further by removing the stubs ?

**Comment by Nakilon** [comment]
Hm, looks like begin-rescue always catches the timeout. So I guess I need to raise an exception class that isn't rescued in my app loop:
```ruby
Timeout.timeout 1, Exception do
```
Still not sure why 1st test in original message did not flunk though.

**Comment by grosser** [comment]
maybe make a new `class TimeoutError < Exception` so errors are readable
